spring:
  application:
    name: blog-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 스프링부트 2.1 이후부턴 MODE = MYSQL 작성 필수
    url: jdbc:mysql://picto-db-2.cj8eomgw4s4w.ap-northeast-2.rds.amazonaws.com:3036/photo_schema?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: rlatmdals456!

  sql:
    init:
      mode: always

  security:
    user:
      name: user
      password: 1234

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    #database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      force-response: true

  port: 8083